### PR TITLE
rewritten

### PR DESCRIPTION
**Pull request by MartijnAB**

### CODE REVIEW

**Review by thomasexner — APPROVED** [review]
There are some typos but overall it looks very nice and more organized than my original code. Thanks a lot. Unfortunately, I could not run it since the reference environment is down again.

**Comment by egonw** [comment]
Thomas, did you see how to indicate the typos by leaving comments on the commit?

**Comment by egonw** [comment]
ping @thomasexner, can this be applied?

**Comment by thomasexner** [comment]
@egonw: I think it is easier if I just correct them. But I need to find the time.

**Pull request merged**
